#!/bin/bash

set -e

# GitHub Rate Limit Exporter - Quick Start Script
# This script helps you get started quickly with the exporter

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="${PROJECT_DIR}/config.yaml"
BINARY_NAME="github_rate_limit_exporter"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Print colored output
print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if required tools are installed
check_requirements() {
    print_info "Checking requirements..."

    if ! command -v go &> /dev/null; then
        print_error "Go is not installed. Please install Go 1.21 or higher."
        exit 1
    fi

    GO_VERSION=$(go version | awk '{print $3}' | sed 's/go//')
    print_info "Found Go version: $GO_VERSION"

    # Check if Task is available
    if command -v task &> /dev/null; then
        print_info "Found Task - will use Taskfile for builds"
        USE_TASK=true
    else
        print_warn "Task not found - using direct go build"
        print_info "Install Task from: https://taskfile.dev"
        USE_TASK=false
    fi
}

# Build the binary
build_binary() {
    print_info "Building ${BINARY_NAME}..."

    cd "$PROJECT_DIR"

    if [ "$USE_TASK" = true ]; then
        if ! task build; then
            print_error "Failed to build binary with Task"
            exit 1
        fi
    else
        mkdir -p build
        if ! go build -o "build/${BINARY_NAME}" ./cmd/exporter; then
            print_error "Failed to build binary"
            exit 1
        fi
    fi

    print_info "Binary built successfully: build/${BINARY_NAME}"
}

# Create configuration file
create_config() {
    if [ -f "$CONFIG_FILE" ]; then
        print_warn "Configuration file already exists at: $CONFIG_FILE"
        read -p "Do you want to overwrite it? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            print_info "Using existing configuration file"
            return
        fi
    fi

    print_info "Creating configuration file..."

    # Prompt for GitHub token
    echo ""
    echo "Please enter your GitHub Personal Access Token(s)."
    echo "You can create one at: https://github.com/settings/tokens"
    echo "Note: No specific scopes are required for reading rate limits."
    echo ""

    USERS=()
    while true; do
        read -p "Enter user name (or press Enter to finish): " USER_NAME
        if [ -z "$USER_NAME" ]; then
            if [ ${#USERS[@]} -eq 0 ]; then
                print_error "At least one user is required"
                continue
            fi
            break
        fi

        read -sp "Enter GitHub token for $USER_NAME: " USER_TOKEN
        echo

        if [ -z "$USER_TOKEN" ]; then
            print_error "Token cannot be empty"
            continue
        fi

        USERS+=("$USER_NAME:$USER_TOKEN")
        print_info "Added user: $USER_NAME"
        echo ""
    done

    # Create YAML config
    cat > "$CONFIG_FILE" << EOF
# GitHub Rate Limit Exporter Configuration
# Generated by quickstart script

users:
EOF

    for USER_ENTRY in "${USERS[@]}"; do
        IFS=':' read -r NAME TOKEN <<< "$USER_ENTRY"
        cat >> "$CONFIG_FILE" << EOF
  - name: "$NAME"
    token: "$TOKEN"
EOF
    done

    cat >> "$CONFIG_FILE" << EOF

# HTTP server configuration
listen_addr: ":9101"        # Address to listen on
metrics_path: "/metrics"    # Path to expose metrics
poll_interval: 60           # Interval in seconds to poll GitHub API
EOF

    # Set secure permissions
    chmod 600 "$CONFIG_FILE"

    print_info "Configuration file created: $CONFIG_FILE"
    print_info "File permissions set to 600 (owner read/write only)"
}

# Run the exporter
run_exporter() {
    print_info "Starting GitHub Rate Limit Exporter..."
    echo ""
    print_info "Metrics will be available at: http://localhost:9101/metrics"
    print_info "Health check at: http://localhost:9101/health"
    echo ""
    print_info "Press Ctrl+C to stop the exporter"
    echo ""

    cd "$PROJECT_DIR"
    "./build/${BINARY_NAME}" -config "$CONFIG_FILE"
}

# Test the configuration
test_config() {
    print_info "Testing configuration..."

    if [ ! -f "$CONFIG_FILE" ]; then
        print_error "Configuration file not found: $CONFIG_FILE"
        exit 1
    fi

    cd "$PROJECT_DIR"

    # Use Task validation if available
    if [ "$USE_TASK" = true ]; then
        print_info "Using Task to validate configuration..."
        if task config:validate 2>/dev/null; then
            print_info "Configuration validation passed"
            return
        fi
    fi

    # Fallback to manual testing
    if ! "./build/${BINARY_NAME}" -config "$CONFIG_FILE" &
    then
        print_error "Failed to start exporter"
        exit 1
    fi

    EXPORTER_PID=$!
    sleep 3

    # Check if process is still running
    if ! kill -0 $EXPORTER_PID 2>/dev/null; then
        print_error "Exporter process died unexpectedly"
        exit 1
    fi

    # Test health endpoint
    if curl -s http://localhost:9101/health > /dev/null; then
        print_info "Health check passed"
    else
        print_error "Health check failed"
        kill $EXPORTER_PID
        exit 1
    fi

    # Test metrics endpoint
    if curl -s http://localhost:9101/metrics | grep -q "github_rate_limit"; then
        print_info "Metrics endpoint working"
    else
        print_warn "Metrics endpoint accessible but no GitHub metrics found yet"
    fi

    # Stop the test instance
    kill $EXPORTER_PID
    wait $EXPORTER_PID 2>/dev/null || true

    print_info "Configuration test completed successfully"
}

# Main menu
show_menu() {
    echo ""
    echo "=========================================="
    echo "  GitHub Rate Limit Exporter - Quick Start"
    echo "=========================================="
    echo ""
    if [ "$USE_TASK" = true ]; then
        echo "  Build tool: Task (Taskfile)"
    else
        echo "  Build tool: Go (direct)"
    fi
    echo ""
    echo "1) Full setup (build + configure + run)"
    echo "2) Build binary only"
    echo "3) Create/update configuration"
    echo "4) Test configuration"
    echo "5) Run exporter (requires existing config)"
    echo "6) Exit"
    echo ""
}

# Main script
main() {
    cd "$PROJECT_DIR"

    if [ $# -eq 0 ]; then
        # Interactive mode
        while true; do
            show_menu
            read -p "Select an option: " choice

            case $choice in
                1)
                    check_requirements
                    build_binary
                    create_config
                    test_config
                    echo ""
                    read -p "Start the exporter now? (Y/n): " -n 1 -r
                    echo
                    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
                        run_exporter
                    fi
                    break
                    ;;
                2)
                    check_requirements
                    build_binary
                    ;;
                3)
                    create_config
                    ;;
                4)
                    check_requirements
                    if [ ! -f "build/${BINARY_NAME}" ]; then
                        print_warn "Binary not found, building..."
                        build_binary
                    fi
                    test_config
                    ;;
                5)
                    if [ ! -f "build/${BINARY_NAME}" ]; then
                        print_error "Binary not found. Please build it first (option 2)"
                        continue
                    fi
                    if [ ! -f "$CONFIG_FILE" ]; then
                        print_error "Configuration file not found. Please create it first (option 3)"
                        continue
                    fi
                    run_exporter
                    break
                    ;;
                6)
                    print_info "Goodbye!"
                    exit 0
                    ;;
                *)
                    print_error "Invalid option"
                    ;;
            esac
        done
    else
        # Command line mode
        case "$1" in
            build)
                check_requirements
                build_binary
                ;;
            config)
                create_config
                ;;
            test)
                check_requirements
                if [ ! -f "build/${BINARY_NAME}" ]; then
                    build_binary
                fi
                test_config
                ;;
            run)
                if [ ! -f "build/${BINARY_NAME}" ]; then
                    print_error "Binary not found. Run: $0 build"
                    exit 1
                fi
                if [ ! -f "$CONFIG_FILE" ]; then
                    print_error "Configuration file not found. Run: $0 config"
                    exit 1
                fi
                run_exporter
                ;;
            all)
                check_requirements
                build_binary
                create_config
                test_config
                run_exporter
                ;;
            *)
                echo "Usage: $0 [build|config|test|run|all]"
                echo ""
                echo "  build  - Build the binary"
                echo "  config - Create configuration file"
                echo "  test   - Test the configuration"
                echo "  run    - Run the exporter"
                echo "  all    - Do everything (build, config, test, run)"
                echo ""
                echo "Run without arguments for interactive mode"
                exit 1
                ;;
        esac
    fi
}

# Run main function
main "$@"
